spring:
  datasource:
    url: jdbc:mysql://localhost:3306/counsel
    username: newuser
    password: password
  jpa:
    hibernate:
#      change this for production
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
  devtools:
    restart:
      enabled: false
  application:
    name: project

server:
  port: 8088
